[package]
name = "app-builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.4.0"
pest_derive = "2.4.0"
tera = "1.17.1"
serde = { version = "1.0", features = ["derive"] }